// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jwt-grpc/proto/auth/auth.proto

package authpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqLogin struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLogin) Reset()         { *m = ReqLogin{} }
func (m *ReqLogin) String() string { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()    {}
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd504ebc4b2d41d3, []int{0}
}

func (m *ReqLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLogin.Unmarshal(m, b)
}
func (m *ReqLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLogin.Marshal(b, m, deterministic)
}
func (m *ReqLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLogin.Merge(m, src)
}
func (m *ReqLogin) XXX_Size() int {
	return xxx_messageInfo_ReqLogin.Size(m)
}
func (m *ReqLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLogin proto.InternalMessageInfo

func (m *ReqLogin) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReqLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RespLogin struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespLogin) Reset()         { *m = RespLogin{} }
func (m *RespLogin) String() string { return proto.CompactTextString(m) }
func (*RespLogin) ProtoMessage()    {}
func (*RespLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd504ebc4b2d41d3, []int{1}
}

func (m *RespLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespLogin.Unmarshal(m, b)
}
func (m *RespLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespLogin.Marshal(b, m, deterministic)
}
func (m *RespLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespLogin.Merge(m, src)
}
func (m *RespLogin) XXX_Size() int {
	return xxx_messageInfo_RespLogin.Size(m)
}
func (m *RespLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_RespLogin.DiscardUnknown(m)
}

var xxx_messageInfo_RespLogin proto.InternalMessageInfo

func (m *RespLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqLogin)(nil), "auth.ReqLogin")
	proto.RegisterType((*RespLogin)(nil), "auth.RespLogin")
}

func init() {
	proto.RegisterFile("jwt-grpc/proto/auth/auth.proto", fileDescriptor_dd504ebc4b2d41d3)
}

var fileDescriptor_dd504ebc4b2d41d3 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcb, 0x2a, 0x2f, 0xd1,
	0x4d, 0x2f, 0x2a, 0x48, 0xd6, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0x2c, 0x2d, 0xc9, 0x00,
	0x13, 0x7a, 0x60, 0xbe, 0x10, 0x0b, 0x88, 0xad, 0xe4, 0xc4, 0xc5, 0x11, 0x94, 0x5a, 0xe8, 0x93,
	0x9f, 0x9e, 0x99, 0x27, 0x24, 0xc5, 0xc5, 0x51, 0x5a, 0x9c, 0x5a, 0x94, 0x97, 0x98, 0x9b, 0x2a,
	0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe7, 0x83, 0xe4, 0x0a, 0x12, 0x8b, 0x8b, 0xcb, 0xf3,
	0x8b, 0x52, 0x24, 0x98, 0x20, 0x72, 0x30, 0xbe, 0x92, 0x22, 0x17, 0x67, 0x50, 0x6a, 0x71, 0x01,
	0xc4, 0x10, 0x11, 0x2e, 0xd6, 0x92, 0xfc, 0xec, 0xd4, 0x3c, 0xa8, 0x09, 0x10, 0x8e, 0x91, 0x39,
	0x17, 0xb7, 0x63, 0x69, 0x49, 0x46, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x06, 0x17,
	0x2b, 0x44, 0x35, 0x9f, 0x1e, 0xd8, 0x45, 0x30, 0x27, 0x48, 0xf1, 0xc3, 0xf8, 0x50, 0xe3, 0x9c,
	0x38, 0xa2, 0xd8, 0x40, 0x22, 0x05, 0x49, 0x49, 0x6c, 0x60, 0x67, 0x1b, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x74, 0xac, 0x94, 0x2a, 0xd8, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	// Unary
	Login(ctx context.Context, in *ReqLogin, opts ...grpc.CallOption) (*RespLogin, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Login(ctx context.Context, in *ReqLogin, opts ...grpc.CallOption) (*RespLogin, error) {
	out := new(RespLogin)
	err := c.cc.Invoke(ctx, "/auth.AuthService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	// Unary
	Login(context.Context, *ReqLogin) (*RespLogin, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) Login(ctx context.Context, req *ReqLogin) (*RespLogin, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqLogin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*ReqLogin))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jwt-grpc/proto/auth/auth.proto",
}
