// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jwt-grpc/proto/hello/hello.proto

package hellopb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqGreet struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGreet) Reset()         { *m = ReqGreet{} }
func (m *ReqGreet) String() string { return proto.CompactTextString(m) }
func (*ReqGreet) ProtoMessage()    {}
func (*ReqGreet) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb58694e4d80eacc, []int{0}
}

func (m *ReqGreet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGreet.Unmarshal(m, b)
}
func (m *ReqGreet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGreet.Marshal(b, m, deterministic)
}
func (m *ReqGreet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGreet.Merge(m, src)
}
func (m *ReqGreet) XXX_Size() int {
	return xxx_messageInfo_ReqGreet.Size(m)
}
func (m *ReqGreet) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGreet.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGreet proto.InternalMessageInfo

func (m *ReqGreet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RespGreet struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespGreet) Reset()         { *m = RespGreet{} }
func (m *RespGreet) String() string { return proto.CompactTextString(m) }
func (*RespGreet) ProtoMessage()    {}
func (*RespGreet) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb58694e4d80eacc, []int{1}
}

func (m *RespGreet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespGreet.Unmarshal(m, b)
}
func (m *RespGreet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespGreet.Marshal(b, m, deterministic)
}
func (m *RespGreet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespGreet.Merge(m, src)
}
func (m *RespGreet) XXX_Size() int {
	return xxx_messageInfo_RespGreet.Size(m)
}
func (m *RespGreet) XXX_DiscardUnknown() {
	xxx_messageInfo_RespGreet.DiscardUnknown(m)
}

var xxx_messageInfo_RespGreet proto.InternalMessageInfo

func (m *RespGreet) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ReqPrimeDecompose struct {
	Number               int64    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqPrimeDecompose) Reset()         { *m = ReqPrimeDecompose{} }
func (m *ReqPrimeDecompose) String() string { return proto.CompactTextString(m) }
func (*ReqPrimeDecompose) ProtoMessage()    {}
func (*ReqPrimeDecompose) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb58694e4d80eacc, []int{2}
}

func (m *ReqPrimeDecompose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqPrimeDecompose.Unmarshal(m, b)
}
func (m *ReqPrimeDecompose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqPrimeDecompose.Marshal(b, m, deterministic)
}
func (m *ReqPrimeDecompose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqPrimeDecompose.Merge(m, src)
}
func (m *ReqPrimeDecompose) XXX_Size() int {
	return xxx_messageInfo_ReqPrimeDecompose.Size(m)
}
func (m *ReqPrimeDecompose) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqPrimeDecompose.DiscardUnknown(m)
}

var xxx_messageInfo_ReqPrimeDecompose proto.InternalMessageInfo

func (m *ReqPrimeDecompose) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type RespPrimeDecompose struct {
	PrimeFactor          int64    `protobuf:"varint,1,opt,name=prime_factor,json=primeFactor,proto3" json:"prime_factor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespPrimeDecompose) Reset()         { *m = RespPrimeDecompose{} }
func (m *RespPrimeDecompose) String() string { return proto.CompactTextString(m) }
func (*RespPrimeDecompose) ProtoMessage()    {}
func (*RespPrimeDecompose) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb58694e4d80eacc, []int{3}
}

func (m *RespPrimeDecompose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespPrimeDecompose.Unmarshal(m, b)
}
func (m *RespPrimeDecompose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespPrimeDecompose.Marshal(b, m, deterministic)
}
func (m *RespPrimeDecompose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespPrimeDecompose.Merge(m, src)
}
func (m *RespPrimeDecompose) XXX_Size() int {
	return xxx_messageInfo_RespPrimeDecompose.Size(m)
}
func (m *RespPrimeDecompose) XXX_DiscardUnknown() {
	xxx_messageInfo_RespPrimeDecompose.DiscardUnknown(m)
}

var xxx_messageInfo_RespPrimeDecompose proto.InternalMessageInfo

func (m *RespPrimeDecompose) GetPrimeFactor() int64 {
	if m != nil {
		return m.PrimeFactor
	}
	return 0
}

type ReqComputeAverage struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqComputeAverage) Reset()         { *m = ReqComputeAverage{} }
func (m *ReqComputeAverage) String() string { return proto.CompactTextString(m) }
func (*ReqComputeAverage) ProtoMessage()    {}
func (*ReqComputeAverage) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb58694e4d80eacc, []int{4}
}

func (m *ReqComputeAverage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqComputeAverage.Unmarshal(m, b)
}
func (m *ReqComputeAverage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqComputeAverage.Marshal(b, m, deterministic)
}
func (m *ReqComputeAverage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqComputeAverage.Merge(m, src)
}
func (m *ReqComputeAverage) XXX_Size() int {
	return xxx_messageInfo_ReqComputeAverage.Size(m)
}
func (m *ReqComputeAverage) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqComputeAverage.DiscardUnknown(m)
}

var xxx_messageInfo_ReqComputeAverage proto.InternalMessageInfo

func (m *ReqComputeAverage) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type RespComputeAverage struct {
	Average              float64  `protobuf:"fixed64,1,opt,name=average,proto3" json:"average,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespComputeAverage) Reset()         { *m = RespComputeAverage{} }
func (m *RespComputeAverage) String() string { return proto.CompactTextString(m) }
func (*RespComputeAverage) ProtoMessage()    {}
func (*RespComputeAverage) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb58694e4d80eacc, []int{5}
}

func (m *RespComputeAverage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespComputeAverage.Unmarshal(m, b)
}
func (m *RespComputeAverage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespComputeAverage.Marshal(b, m, deterministic)
}
func (m *RespComputeAverage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespComputeAverage.Merge(m, src)
}
func (m *RespComputeAverage) XXX_Size() int {
	return xxx_messageInfo_RespComputeAverage.Size(m)
}
func (m *RespComputeAverage) XXX_DiscardUnknown() {
	xxx_messageInfo_RespComputeAverage.DiscardUnknown(m)
}

var xxx_messageInfo_RespComputeAverage proto.InternalMessageInfo

func (m *RespComputeAverage) GetAverage() float64 {
	if m != nil {
		return m.Average
	}
	return 0
}

type ReqFindMax struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqFindMax) Reset()         { *m = ReqFindMax{} }
func (m *ReqFindMax) String() string { return proto.CompactTextString(m) }
func (*ReqFindMax) ProtoMessage()    {}
func (*ReqFindMax) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb58694e4d80eacc, []int{6}
}

func (m *ReqFindMax) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqFindMax.Unmarshal(m, b)
}
func (m *ReqFindMax) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqFindMax.Marshal(b, m, deterministic)
}
func (m *ReqFindMax) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqFindMax.Merge(m, src)
}
func (m *ReqFindMax) XXX_Size() int {
	return xxx_messageInfo_ReqFindMax.Size(m)
}
func (m *ReqFindMax) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqFindMax.DiscardUnknown(m)
}

var xxx_messageInfo_ReqFindMax proto.InternalMessageInfo

func (m *ReqFindMax) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type RespFindMax struct {
	MaxNumber            int32    `protobuf:"varint,1,opt,name=max_number,json=maxNumber,proto3" json:"max_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespFindMax) Reset()         { *m = RespFindMax{} }
func (m *RespFindMax) String() string { return proto.CompactTextString(m) }
func (*RespFindMax) ProtoMessage()    {}
func (*RespFindMax) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb58694e4d80eacc, []int{7}
}

func (m *RespFindMax) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespFindMax.Unmarshal(m, b)
}
func (m *RespFindMax) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespFindMax.Marshal(b, m, deterministic)
}
func (m *RespFindMax) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespFindMax.Merge(m, src)
}
func (m *RespFindMax) XXX_Size() int {
	return xxx_messageInfo_RespFindMax.Size(m)
}
func (m *RespFindMax) XXX_DiscardUnknown() {
	xxx_messageInfo_RespFindMax.DiscardUnknown(m)
}

var xxx_messageInfo_RespFindMax proto.InternalMessageInfo

func (m *RespFindMax) GetMaxNumber() int32 {
	if m != nil {
		return m.MaxNumber
	}
	return 0
}

func init() {
	proto.RegisterType((*ReqGreet)(nil), "hello.ReqGreet")
	proto.RegisterType((*RespGreet)(nil), "hello.RespGreet")
	proto.RegisterType((*ReqPrimeDecompose)(nil), "hello.ReqPrimeDecompose")
	proto.RegisterType((*RespPrimeDecompose)(nil), "hello.RespPrimeDecompose")
	proto.RegisterType((*ReqComputeAverage)(nil), "hello.ReqComputeAverage")
	proto.RegisterType((*RespComputeAverage)(nil), "hello.RespComputeAverage")
	proto.RegisterType((*ReqFindMax)(nil), "hello.ReqFindMax")
	proto.RegisterType((*RespFindMax)(nil), "hello.RespFindMax")
}

func init() {
	proto.RegisterFile("jwt-grpc/proto/hello/hello.proto", fileDescriptor_eb58694e4d80eacc)
}

var fileDescriptor_eb58694e4d80eacc = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4b, 0x4f, 0xc2, 0x40,
	0x10, 0xa6, 0x2a, 0xd4, 0x0e, 0x44, 0x65, 0x0f, 0xa6, 0x92, 0x68, 0x70, 0xa3, 0x09, 0xf1, 0x01,
	0x44, 0x13, 0x3d, 0xfb, 0x08, 0xea, 0x41, 0x63, 0xd6, 0x9b, 0x17, 0xb2, 0xd4, 0x11, 0x31, 0x2c,
	0x5d, 0xb6, 0x05, 0xf9, 0x09, 0xfe, 0x6c, 0xd3, 0x6d, 0x97, 0xb2, 0x4d, 0xbc, 0x34, 0x33, 0xdf,
	0x6b, 0xd2, 0xaf, 0x85, 0xe6, 0xf7, 0x4f, 0x7c, 0x3e, 0x54, 0x32, 0xe8, 0x48, 0x15, 0xc6, 0x61,
	0xe7, 0x0b, 0xc7, 0xe3, 0xec, 0xd9, 0xd6, 0x08, 0x29, 0xeb, 0x85, 0x1e, 0xc0, 0x26, 0xc3, 0xe9,
	0x83, 0x42, 0x8c, 0x09, 0x81, 0x8d, 0x09, 0x17, 0xe8, 0x3b, 0x4d, 0xa7, 0xe5, 0x31, 0x3d, 0xd3,
	0x63, 0xf0, 0x18, 0x46, 0x32, 0x15, 0xf8, 0xe0, 0x0a, 0x8c, 0x22, 0x3e, 0x34, 0x1a, 0xb3, 0xd2,
	0x53, 0xa8, 0x33, 0x9c, 0xbe, 0xaa, 0x91, 0xc0, 0x7b, 0x0c, 0x42, 0x21, 0xc3, 0x08, 0xc9, 0x2e,
	0x54, 0x26, 0x33, 0x31, 0x40, 0xa5, 0xd5, 0xeb, 0x2c, 0xdb, 0xe8, 0x35, 0x90, 0x24, 0xb3, 0xa0,
	0x3e, 0x84, 0x9a, 0x4c, 0x90, 0xfe, 0x27, 0x0f, 0xe2, 0xd0, 0x78, 0xaa, 0x1a, 0xeb, 0x69, 0x28,
	0xbb, 0x72, 0x17, 0x0a, 0x39, 0x8b, 0xf1, 0x66, 0x8e, 0x8a, 0x0f, 0x8b, 0x57, 0xca, 0xcb, 0x2b,
	0xed, 0xf4, 0x4a, 0x41, 0xed, 0x83, 0xcb, 0xd3, 0x51, 0xcb, 0x1d, 0x66, 0x56, 0x7a, 0x04, 0xc0,
	0x70, 0xda, 0x1b, 0x4d, 0x3e, 0x9e, 0xf9, 0xe2, 0xdf, 0xd4, 0x33, 0xa8, 0x26, 0xa9, 0x46, 0xb6,
	0x0f, 0x20, 0xf8, 0xa2, 0x6f, 0x49, 0x3d, 0xc1, 0x17, 0x2f, 0x1a, 0xb8, 0xf8, 0x5d, 0x83, 0xda,
	0x63, 0xd2, 0xf3, 0x1b, 0xaa, 0xf9, 0x28, 0x40, 0x72, 0x02, 0xe5, 0xb4, 0xca, 0xed, 0x76, 0xfa,
	0x31, 0x4c, 0xf9, 0x8d, 0x9d, 0x25, 0x60, 0xda, 0x7e, 0x82, 0xad, 0x42, 0x45, 0x7e, 0x6e, 0xb2,
	0x99, 0xc6, 0xde, 0x8a, 0xdb, 0xa6, 0x68, 0xa9, 0xeb, 0x24, 0x51, 0xc5, 0x1e, 0xf2, 0x28, 0x9b,
	0xb1, 0xa2, 0x6c, 0x8a, 0x96, 0x5a, 0x0e, 0xb9, 0x02, 0xd7, 0xbc, 0x7c, 0x3d, 0xcf, 0xc8, 0xa0,
	0x06, 0x59, 0x31, 0x67, 0x58, 0xe2, 0xea, 0x3a, 0xb7, 0xde, 0xbb, 0xab, 0x29, 0x39, 0x18, 0x54,
	0xf4, 0x1f, 0x78, 0xf9, 0x17, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x74, 0x83, 0x16, 0xa5, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloServiceClient interface {
	// Unary
	Greet(ctx context.Context, in *ReqGreet, opts ...grpc.CallOption) (*RespGreet, error)
	// Server Stream
	PrimeDecompose(ctx context.Context, in *ReqPrimeDecompose, opts ...grpc.CallOption) (HelloService_PrimeDecomposeClient, error)
	// Client Stream
	ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (HelloService_ComputeAverageClient, error)
	// Bi Directional Stream
	FindMax(ctx context.Context, opts ...grpc.CallOption) (HelloService_FindMaxClient, error)
}

type helloServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloServiceClient(cc grpc.ClientConnInterface) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) Greet(ctx context.Context, in *ReqGreet, opts ...grpc.CallOption) (*RespGreet, error) {
	out := new(RespGreet)
	err := c.cc.Invoke(ctx, "/hello.HelloService/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloServiceClient) PrimeDecompose(ctx context.Context, in *ReqPrimeDecompose, opts ...grpc.CallOption) (HelloService_PrimeDecomposeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HelloService_serviceDesc.Streams[0], "/hello.HelloService/PrimeDecompose", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloServicePrimeDecomposeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HelloService_PrimeDecomposeClient interface {
	Recv() (*RespPrimeDecompose, error)
	grpc.ClientStream
}

type helloServicePrimeDecomposeClient struct {
	grpc.ClientStream
}

func (x *helloServicePrimeDecomposeClient) Recv() (*RespPrimeDecompose, error) {
	m := new(RespPrimeDecompose)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloServiceClient) ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (HelloService_ComputeAverageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HelloService_serviceDesc.Streams[1], "/hello.HelloService/ComputeAverage", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloServiceComputeAverageClient{stream}
	return x, nil
}

type HelloService_ComputeAverageClient interface {
	Send(*ReqComputeAverage) error
	CloseAndRecv() (*RespComputeAverage, error)
	grpc.ClientStream
}

type helloServiceComputeAverageClient struct {
	grpc.ClientStream
}

func (x *helloServiceComputeAverageClient) Send(m *ReqComputeAverage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helloServiceComputeAverageClient) CloseAndRecv() (*RespComputeAverage, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(RespComputeAverage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloServiceClient) FindMax(ctx context.Context, opts ...grpc.CallOption) (HelloService_FindMaxClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HelloService_serviceDesc.Streams[2], "/hello.HelloService/FindMax", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloServiceFindMaxClient{stream}
	return x, nil
}

type HelloService_FindMaxClient interface {
	Send(*ReqFindMax) error
	Recv() (*RespFindMax, error)
	grpc.ClientStream
}

type helloServiceFindMaxClient struct {
	grpc.ClientStream
}

func (x *helloServiceFindMaxClient) Send(m *ReqFindMax) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helloServiceFindMaxClient) Recv() (*RespFindMax, error) {
	m := new(RespFindMax)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HelloServiceServer is the server API for HelloService service.
type HelloServiceServer interface {
	// Unary
	Greet(context.Context, *ReqGreet) (*RespGreet, error)
	// Server Stream
	PrimeDecompose(*ReqPrimeDecompose, HelloService_PrimeDecomposeServer) error
	// Client Stream
	ComputeAverage(HelloService_ComputeAverageServer) error
	// Bi Directional Stream
	FindMax(HelloService_FindMaxServer) error
}

// UnimplementedHelloServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServiceServer struct {
}

func (*UnimplementedHelloServiceServer) Greet(ctx context.Context, req *ReqGreet) (*RespGreet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}
func (*UnimplementedHelloServiceServer) PrimeDecompose(req *ReqPrimeDecompose, srv HelloService_PrimeDecomposeServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeDecompose not implemented")
}
func (*UnimplementedHelloServiceServer) ComputeAverage(srv HelloService_ComputeAverageServer) error {
	return status.Errorf(codes.Unimplemented, "method ComputeAverage not implemented")
}
func (*UnimplementedHelloServiceServer) FindMax(srv HelloService_FindMaxServer) error {
	return status.Errorf(codes.Unimplemented, "method FindMax not implemented")
}

func RegisterHelloServiceServer(s *grpc.Server, srv HelloServiceServer) {
	s.RegisterService(&_HelloService_serviceDesc, srv)
}

func _HelloService_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGreet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.HelloService/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).Greet(ctx, req.(*ReqGreet))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloService_PrimeDecompose_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReqPrimeDecompose)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HelloServiceServer).PrimeDecompose(m, &helloServicePrimeDecomposeServer{stream})
}

type HelloService_PrimeDecomposeServer interface {
	Send(*RespPrimeDecompose) error
	grpc.ServerStream
}

type helloServicePrimeDecomposeServer struct {
	grpc.ServerStream
}

func (x *helloServicePrimeDecomposeServer) Send(m *RespPrimeDecompose) error {
	return x.ServerStream.SendMsg(m)
}

func _HelloService_ComputeAverage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloServiceServer).ComputeAverage(&helloServiceComputeAverageServer{stream})
}

type HelloService_ComputeAverageServer interface {
	SendAndClose(*RespComputeAverage) error
	Recv() (*ReqComputeAverage, error)
	grpc.ServerStream
}

type helloServiceComputeAverageServer struct {
	grpc.ServerStream
}

func (x *helloServiceComputeAverageServer) SendAndClose(m *RespComputeAverage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helloServiceComputeAverageServer) Recv() (*ReqComputeAverage, error) {
	m := new(ReqComputeAverage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _HelloService_FindMax_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloServiceServer).FindMax(&helloServiceFindMaxServer{stream})
}

type HelloService_FindMaxServer interface {
	Send(*RespFindMax) error
	Recv() (*ReqFindMax, error)
	grpc.ServerStream
}

type helloServiceFindMaxServer struct {
	grpc.ServerStream
}

func (x *helloServiceFindMaxServer) Send(m *RespFindMax) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helloServiceFindMaxServer) Recv() (*ReqFindMax, error) {
	m := new(ReqFindMax)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _HelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hello.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _HelloService_Greet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeDecompose",
			Handler:       _HelloService_PrimeDecompose_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ComputeAverage",
			Handler:       _HelloService_ComputeAverage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "FindMax",
			Handler:       _HelloService_FindMax_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "jwt-grpc/proto/hello/hello.proto",
}
